version: "3"
services:
  # 单机跑demo , 要调大docker内存，否则nacos会闪退
  nacos:
    container_name: nacos
    hostname: nacos
#    image: nacos/nacos-server:v2.3.0
    image: nacos/nacos-server:v2.3.0-slim   # apple silicon
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo_appactiive_pw
      MYSQL_DATABASE: product
    ports:
      - "3306:3306"
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]

  sharding-proxy:
    image: apache/shardingsphere-proxy:5.4.1
    container_name: sharding-proxy
    ports:
      - 3307:3307
    volumes:
      - ./sharding-proxy/conf:/opt/shardingsphere-proxy/conf
      - ./sharding-proxy/ext-lib:/opt/shardingsphere-proxy/ext-lib

  gateway:
    build: ./gateway
    container_name: gateway
    hostname: gateway
    image: app-active/gateway:0.2.1
    ports:
      - "80:80"
      - "8090:8090"
    depends_on:
      - "nacos"
      - "frontend"

  order:
    build: ./order
    image: app-active/order:0.2.1
    container_name: order
    hostname: order
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
#      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&activeInstanceId=mysql&activeDbName=product
      - appactive.unit=center
      - appactive.app=order
      - appactive.configServerAddress=nacos:8848
      - server.port=8881
    ports:
      - "8881:8881"
    depends_on:
      - "nacos"
      - "mysql"

  order-unit:
    image: app-active/order:0.2.1
    container_name: order-unit
    hostname: order-unit
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
#      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&activeInstanceId=mysql&activeDbName=product
      - appactive.unit=unit
      - appactive.app=order
      - appactive.configServerAddress=nacos:8848
      - server.port=8882
    ports:
      - "8882:8882"
    depends_on:
      - "nacos"
      - "mysql"

  product:
    build: ./product
    image: app-active/product:0.2.1
    container_name: product
    hostname: product
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      - appactive.unit=center
      - appactive.app=product
      - appactive.configServerAddress=nacos:8848
      - server.port=8883
    ports:
      - "8883:8883"
    depends_on:
      - "nacos"
      - "mysql"
      - "order"

  product-unit:
    image: app-active/product:0.2.1
    container_name: product-unit
    hostname: product-unit
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.datasource.url=jdbc:mysql://mysql:3306/product?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      - appactive.unit=unit
      - appactive.app=product
      - appactive.configServerAddress=nacos:8848
      - server.port=8884
    ports:
      - "8884:8884"
    depends_on:
      - "nacos"
      - "mysql"
      - "order-unit"

  frontend:
    build: ./frontend
    image: app-active/frontend:0.2.1
    container_name: frontend
    hostname: frontend
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - appactive.unit=center
      - appactive.app=frontend
      - appactive.configServerAddress=nacos:8848
      - io.appactive.demo.unitlist=center,unit
      - io.appactive.demo.applist=frontend,product,order
      - server.port=8885
    ports:
      - "8885:8885"
    depends_on:
      - "nacos"
      - "product"

  frontend-unit:
    image: app-active/frontend:0.2.1
    container_name: frontend-unit
    hostname: frontend-unit
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - appactive.unit=unit
      - appactive.app=frontend
      - appactive.configServerAddress=nacos:8848
      - io.appactive.demo.unitlist=center,unit
      - io.appactive.demo.applist=frontend,product,order
      - server.port=8886
    ports:
      - "8886:8886"
    depends_on:
      - "nacos"
      - "product-unit"
